version: "3.0"
services:
  db:
    image: mysql:8
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: EVADON
      MYSQL_USER: sa
      MYSQL_PASSWORD: sa
    expose:
      - "3306"
    volumes:
      - /Home/bong/evadon/mysql:/var/lib/mysql/
  evadon-server:
    build: "./evadon_web/"
    ports:
      - "8080:8080"
    depends_on:
      - db
    command: ["./wait-for-it.sh", "db:3306"]
  evadon-front:
    build: "./evadon-front/"
    ports:
      - "80:80"
    depends_on:
      - evadon-server
