version: "3.0"
services:
  db:
    image: mysql:8
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: EVADON
      MYSQL_USER: sa
      MYSQL_PASSWORD: sa
    ports:
      - "3306:3306"
  evadon-auto:
    build: .
    ports:
      - "8000:8080"
    depends_on:
      - db
    command: ["./wait-for-it.sh", "db:3306"]
