version: "3.0"
services:
  db:
    image: mysql:11
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: sa
      MYSQL_PASSWORD: sa
      MYSQL_DATABASE: EVADON
    ports:
      - 3306:3306
  service-a:
    build: .
    restart: on-failure
    links:
      - db
    depends_on:
      - db