version: "3.0"
services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: EVADON
      MYSQL_USER: sa
      MYSQL_PASSWORD: sa
    ports:
      - 3306:3306
  evadon-auto:
    build: .
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - db